# Header
menu:
  Home: /
  About: /about
  Contact: /contact

# Favicon
favicon_url: images/favicon.png

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics: UA-63669606-1

# Social Accounts
email_url:
twitter_url: https://twitter.com/thomcrowe
facebook_url: https://www.facebook.com/thomcrowe
instagram_url: https://www.instagram.com/thomcrowe
linkedin_url: https://www.linkedin.com/thomcrowe
dribbble_url:
github_url: https://www.github.com/thomcrowe
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname:

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page
